pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=eikek-scala-steward
    actions:
      assign:
        users: [eikek]
      label:
        add: ["type: dependencies"]
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=apps/eikek-scala-steward
      - base=master
      - status-success=ci
    actions:
      merge:
        method: merge
  - name: automatically merge my (eikek) PRs on CI success
    conditions:
      - author=eikek
      - base=master
      - status-success=ci
    actions:
      merge:
        method: merge
