ALTER TABLE `item`
MODIFY `itemdate` TIMESTAMP NULL;

ALTER TABLE `item`
MODIFY `duedate` TIMESTAMP NULL;

ALTER TABLE `user_`
MODIFY `lastlogin` TIMESTAMP NULL;

ALTER TABLE `job`
MODIFY `started` TIMESTAMP NULL;

ALTER TABLE `job`
MODIFY `finished` TIMESTAMP NULL;
